# Generated by Django 2.1.1 on 2018-09-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='ninjas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codingdojo', to='first_app.Ninja'),
        ),
    ]
