# Generated by Django 2.1.1 on 2018-09-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180914_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='ninjas',
        ),
        migrations.DeleteModel(
            name='Dojo',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codingdojo', to='first_app.Dojos'),
        ),
    ]
